version: '2'
services:
  start:
    build: .
    image: html-to-pdf
    command: npm start
    ports:
    - "80:80"
    mem_limit: 1028m
    restart: always

  test:
    build: .
    image: html-to-pdf
    command: npm test
    volumes:
    - ./test:/home/test
    - ./index.js:/home/index.js
    - ./styles.css:/home/styles.css