version: '2'
services:
  debug:
    build: .
    image: html-to-pdf
    command: node --debug=0.0.0.0:9229 --debug-brk ./test/test.js
    ports:
    - "9229:9229"
    volumes:
    - ./test:/home/test
    - ./converter.js:/home/converter.js
    - ./style.js:/home/style.js
    - ./package.json:/home/package.json
  env:
    build: .
    image: html-to-pdf
    command: /bin/bash
    volumes:
    - ./:/home
  start:
    build: .
    image: html-to-pdf
    command: npm start -- 9050
    ports:
    - "9050:9050"
    mem_limit: 1028m
    restart: always