version: '2'
services:
  start:
    build: .
    image: html-to-pdf
    command: /bin/bash
    ports:
    - "9229:9229"
    volumes:
    - ./test:/home/test
    - ./index.js:/home/index.js
    - ./styles.css:/home/styles.css
    - ./package.json:/home/package.json
    restart: always