version: '2'
services:
  debug:
    build: .
    image: html-to-pdf
    command: node --debug=0.0.0.0:9229 --debug-brk ./test/test.js
    ports:
    - "9229:9229"
    volumes:
    - ./test:/home/test
    - ./index.js:/home/index.js
    - ./styles.css:/home/styles.css
    - ./package.json:/home/package.json
    restart: always
  env:
    build: .
    image: html-to-pdf
    command: /bin/bash